# Jekyll Configuration for Documentation Projects

# Site settings
title: Documentation Hub
email: your-email@example.com
description: >-
  A central repository for all my documentation projects, including guides, 
  notes, and reference materials organized for easy access.
baseurl: "/documentation-projects"
url: "https://raytogether.github.io"
github_username: Raytogether

# Build settings
theme: minima
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Layout defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Collections
collections:
  warp:
    output: true
    permalink: /warp/:path/
  learning:
    output: true
    permalink: /learning/:path/
  backup-strategy:
    output: true
    permalink: /backup-strategy/:path/
  ssh:
    output: true
    permalink: /ssh/:path/

# Navigation structure
header_pages:
  - index.md
  - backup-strategy/index.md
  - warp/keyboard-shortcuts/index.md
  - warp/tips-tricks/index.md
  - learning/git-journey/index.md
  - learning/journey-to-code/index.md
  - ssh/index.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - _site/
  - drafts/
  - "*.tmp"
  - "*.temp"
  - "*.swp"
  - "*.bak"
  - "*.backup"
  - "*.log"
  - "logs/"
  - "__pycache__/"
  - "*.py[cod]"
  - "*$py.class"
  - ".env*"
  - "*.sublime-*"
  - "*.code-workspace"
  - ".vscode/"
  - ".idea/"

